podSecurityPolicy:
  enabled: false
alertmanager:
  enabled: false
alertmanagerFiles:
  alertmanager.yml: ""
configmapReload:
  alertmanager:
    enabled: false
kubeStateMetrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
server:
  persistentVolume:
    enabled: false
prometheus-pushgateway:
  enabled: false
